var PRODUCTS_LIST = [
  {
    id: 1,
    title: "RECYCLED POLYESTER PARKA 1",
    price: 135,
    image: "../assets/images/women-product-1.png",
    image2: "../assets/images/women-product-1.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-fashion-1.png",
    otherimg2: "../assets/images/women-fashion-2.png",
    otherimg3: "../assets/images/women-fashion-3.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps.   - Relaxed fit    - Dropped shoulder   - Elasticated body   - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
  {
    id: 2,
    title: "RECYCLED POLYESTER PARKA 2",
    price: 125,
    image: "../assets/images/women-fashion-1.png",
    image2: "../assets/images/women-fashion-1.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-product-1.png",
    otherimg2: "../assets/images/women-fashion-2.png",
    otherimg3: "../assets/images/women-fashion-3.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps. - Relaxed fit - Dropped shoulder - Elasticated body - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
  {
    id: 3,
    title: "RECYCLED POLYESTER PARKA 3",
    price: 145,
    image: "../assets/images/women-fashion-2.png",
    image2: "../assets/images/women-fashion-2.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-fashion-1.png",
    otherimg2: "../assets/images/women-product-1.png",
    otherimg3: "../assets/images/women-fashion-3.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps. - Relaxed fit - Dropped shoulder - Elasticated body - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
  {
    id: 4,
    title: "RECYCLED POLYESTER PERFORMANCE 4",
    price: 145,
    image: "../assets/images/women-fashion-3.png",
    image2: "../assets/images/women-fashion-3.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-fashion-1.png",
    otherimg2: "../assets/images/women-fashion-2.png",
    otherimg3: "../assets/images/women-product-1.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps. - Relaxed fit - Dropped shoulder - Elasticated body - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
  {
    id: 5,
    title: "RECYCLED POLYESTER PERFORMANCE 5",
    price: 115,
    image: "../assets/images/women-product-1.png",
    image2: "../assets/images/women-product-1.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-fashion-1.png",
    otherimg2: "../assets/images/women-fashion-2.png",
    otherimg3: "../assets/images/women-fashion-3.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps. - Relaxed fit - Dropped shoulder - Elasticated body - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
  {
    id: 6,
    title: "RECYCLED PERFORMANCE PARKA 6",
    price: 145,
    image: "../assets/images/women-fashion-1.png",
    image2: "../assets/images/women-fashion-1.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-product-1.png",
    otherimg2: "../assets/images/women-fashion-2.png",
    otherimg3: "../assets/images/women-fashion-3.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps. - Relaxed fit - Dropped shoulder - Elasticated body - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
  {
    id: 7,
    title: "RECYCLED PERFORMANCE PARKA 7",
    price: 145,
    image: "../assets/images/women-fashion-2.png",
    image2: "../assets/images/women-fashion-2.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-fashion-1.png",
    otherimg2: "../assets/images/women-product-1.png",
    otherimg3: "../assets/images/women-fashion-3.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps. - Relaxed fit - Dropped shoulder - Elasticated body - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
  {
    id: 8,
    title: "RECYCLED POLYESTER PARKA 8",
    price: 145,
    image: "../assets/images/women-fashion-3.png",
    image2: "../assets/images/women-fashion-3.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-fashion-1.png",
    otherimg2: "../assets/images/women-fashion-2.png",
    otherimg3: "../assets/images/women-product-1.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps. - Relaxed fit - Dropped shoulder - Elasticated body - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
  {
    id: 9,
    title: "RECYCLED POLYESTER PERFORMANCE 9",
    price: 145,
    image: "../assets/images/women-product-1.png",
    image2: "../assets/images/women-product-1.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-fashion-1.png",
    otherimg2: "../assets/images/women-fashion-2.png",
    otherimg3: "../assets/images/women-fashion-3.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps. - Relaxed fit - Dropped shoulder - Elasticated body - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
  {
    id: 10,
    title: "POLYESTER PERFORMANCE PARKA 10",
    price: 165,
    image: "../assets/images/women-fashion-1.png",
    image2: "../assets/images/women-fashion-1.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-product-1.png",
    otherimg2: "../assets/images/women-fashion-2.png",
    otherimg3: "../assets/images/women-fashion-3.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps. - Relaxed fit - Dropped shoulder - Elasticated body - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
  {
    id: 11,
    title: "RECYCLED PERFORMANCE PARKA 11",
    price: 155,
    image: "../assets/images/women-fashion-2.png",
    image2: "../assets/images/women-fashion-2.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-fashion-1.png",
    otherimg2: "../assets/images/women-product-1.png",
    otherimg3: "../assets/images/women-fashion-3.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps. - Relaxed fit - Dropped shoulder - Elasticated body - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
  {
    id: 12,
    title: "RECYCLED POLYESTER PERFORMANCE 12",
    price: 125,
    image: "../assets/images/women-fashion-3.png",
    image2: "../assets/images/women-fashion-3.png",
    image3: "../assets/images/women-product-2.png",
    image4: "../assets/images/women-product-3.png",
    image5: "../assets/images/women-product-4.png",
    image6: "../assets/images/women-product-5.png",
    otherimg1: "../assets/images/women-fashion-1.png",
    otherimg2: "../assets/images/women-fashion-2.png",
    otherimg3: "../assets/images/women-product-1.png",
    description:
      "Crafted from an organic cotton-mulberry silk mix, this oversized cardigan features a elasticated body and dropped shoulder. Effortlessly style with tonal shorts and pumps. - Relaxed fit - Dropped shoulder - Elasticated body - Ribbed cuff 32% Polyamide, 29% Viscose, 23% Mulberry silk, 15% Organic cotton, 1% Elastane / Machine washable Back length of size XS/S is 70cm ",
    description2:
      "32% Polyamide / 29% Viscose / 23% Silk / 15% Cotton / 1% Elastane / Machine washable Make sure that your favourite items remain long-loved pieces for years to come; read our product care guide and explore our selection of carefully chosen care products. Product No: 0930647001 ",
  },
];
